name: 'house_price_dwh'
version: '1.0.0'
config-version: 2

profile: 'house_price_dwh'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  house_price_dwh:
    bronze:
      +materialized: table
    silver:
      +materialized: table
    gold:
      +materialized: table

seeds:
  house_price_dwh:
    +schema: raw 