name: 'house_price_dwh'
version: '1.0.0'
config-version: 2

profile: 'house_price_dwh'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  +materialized: table
  staging:
    +schema: stg
    +materialized: view
  intermediate:
    +schema: int
  marts:
    +schema: mart
    +tags: ["ml"]

seeds:
  +schema: raw
  house_data:
    +column_types:
      price: integer
      sqft: integer
      bedrooms: integer
      bathrooms: float
      location: varchar
      year_built: integer
      condition: varchar 