# =============================================================================
# simple-dwh-mlops - 共通設定ファイル
# =============================================================================

# プロジェクト基本設定
project:
  name: "simple-dwh-mlops"
  version: "1.0.0"
  description: "機械学習による住宅価格予測システム"
  author: "MLOps Team"
  license: "MIT"

# 依存関係設定
dependencies:
  requirements_file: "configs/requirements.txt"
  python_version: "3.12.3"

# 仮想環境設定
venv:
  path: ".venv"
  python_version: "3.12.3"

# データ設定
data:
  # 生データ設定
  raw:
    path: "data/raw"
    file_name: "house_price_data.csv"
    encoding: "utf-8"

# データベース設定
database:
  type: "duckdb"
  path: "models/trained/house_price_dwh.duckdb"
  connection:
    read_only: false
    memory: false

# 機械学習基本設定
ml:
  # 特徴量設定
  features:
    target_column: "price"
    categorical_columns: []
    numerical_columns: []
    drop_columns: []
  
  # モデル基本設定
  model:
    save_path: "models/trained"
    model_name: "house_price_model"
    version: "latest"
  
  # 評価メトリクス
  evaluation:
    metrics:
      - "mae"
      - "mse"
      - "rmse"
      - "r2"
      - "mape"
    threshold:
      r2_min: 0.7
      mae_max: 100000

# ログ設定
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/app.log"
  max_size: "10MB"
  backup_count: 5

# パフォーマンス設定
performance:
  batch_size: 1000
  max_workers: 4
  cache_enabled: true
  cache_ttl: 3600
  n_jobs: -1 