# =============================================================================
# House Price Predictor - データ設定
# =============================================================================

# データベース設定
database:
  type: "duckdb"
  path: "data/interim/house_price_dwh.duckdb"
  connection:
    read_only: false
    memory: false

# MLflow設定
mlflow:
  tracking_uri: "http://localhost:5555"
  experiment_name: "house-prices-mlops"
  artifact_location: "models/artifacts"
  
  # データストア設定
  backend_store_uri: "sqlite:///mlflow.db"
  default_artifact_root: "mlruns"
  
  # アーティファクト設定
  artifacts:
    local:
      enabled: true
      path: "mlruns"
      
  # モデルレジストリ設定
  model_registry:
    enabled: true
    backend_store_uri: "sqlite:///mlflow.db"
    
  # 実験管理設定
  experiments:
    auto_create: true
    default_experiment: "house-prices-mlops"
    
  # ログ設定
  logging:
    level: "INFO"
    format: "json"
    file: "logs/mlflow.log"
    
  # セキュリティ設定
  security:
    enable_proxy: false
    trusted_hosts: ["localhost", "127.0.0.1"]
    
  # パフォーマンス設定
  performance:
    max_artifact_size: "1GB"
    max_parameter_size: "250KB"
    max_metric_size: "250KB"

# アプリケーション設定
app:
  name: "house-prices-mlops"
  version: "1.0.0"
  environment: "development"
  debug: true
  root_path: "/home/wsl/dev/mlops/simple-dwh-mlops" 