# =============================================================================
# House Price Predictor - アンサンブルモデル設定
# =============================================================================

# アンサンブル基本設定
ensemble:
  name: "house_price_ensemble_duckdb"
  target_variable: "price"
  method: "stacking"  # voting, stacking, blending
  voting_method: "soft"  # soft, hard (for voting ensemble)
  version: "1.0.0"

# ベースモデル設定
base_models:
  RandomForest:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 42
    n_jobs: -1
    weight: 0.3
    enabled: true
    
  XGBoost:
    n_estimators: 200
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42
    n_jobs: -1
    weight: 0.4
    enabled: true
    
  GradientBoosting:
    n_estimators: 150
    max_depth: 5
    learning_rate: 0.05
    subsample: 0.8
    random_state: 42
    weight: 0.3
    enabled: true

# スタッキング設定（methodがstackingの場合）
stacking:
  meta_model: "LinearRegression"
  cv_folds: 5
  use_probas: false
  passthrough: false
  stack_method: "predict"

# 訓練設定
training:
  test_size: 0.2
  random_state: 42
  cv_folds: 5
  cross_validation: true
  shuffle: true
  stratify: null

# モデル評価設定
evaluation:
  # 評価メトリクス
  metrics:
    - "mae"
    - "r2"
    - "rmse"
    - "mape"
  
  # 閾値設定
  thresholds:
    r2_min: 0.7
    mae_max: 100000
    rmse_max: 150000
  
  # 評価方法
  methods:
    - "cross_validation"
    - "holdout_test"
    - "bootstrap"

# アンサンブル固有設定
ensemble_specific:
  # 重み最適化
  optimize_weights: true
  weight_optimization_method: "grid_search"
  
  # モデル選択
  model_selection:
    enable_feature_selection: true
    feature_selection_method: "recursive"
    max_features: 10
  
  # 予測設定
  prediction:
    use_confidence_intervals: true
    confidence_level: 0.95
    return_individual_predictions: false 