version: 2

sources:
  - name: bronze
    description: "Bronze layer raw data"
    database: house_price_dwh
    schema: main
    tables:
      - name: bronze_raw_house_data
        description: "Raw house data from bronze layer"
        columns:
          - name: id
            description: "Primary key"
            tests:
              - not_null
              - unique
          - name: price
            description: "House price in USD"
          - name: sqft
            description: "Square footage"
          - name: bedrooms
            description: "Number of bedrooms"
          - name: bathrooms
            description: "Number of bathrooms"
          - name: location
            description: "Location of the house"
          - name: year_built
            description: "Year the house was built"
          - name: condition
            description: "Condition of the house"
          - name: created_at
            description: "Record creation timestamp" 