version: 2

sources:
  - name: raw
    description: "Raw data from CSV files and external sources"
    database: house_price_dwh
    schema: main_raw
    tables:
      - name: house_data
        description: "Raw house data from CSV seed file"
        columns:
          - name: price
            description: "House price in USD"
            tests:
              - not_null
          - name: sqft
            description: "Square footage"
            tests:
              - not_null
          - name: bedrooms
            description: "Number of bedrooms"
            tests:
              - not_null
          - name: bathrooms
            description: "Number of bathrooms"
            tests:
              - not_null
          - name: location
            description: "Location name"
            tests:
              - not_null
          - name: year_built
            description: "Year the house was built"
            tests:
              - not_null
          - name: condition
            description: "House condition"
            tests:
              - not_null 